### ISSUE TITLE
Execution issue "No module name board"

### ISSUE THREAD

**Issue by hpsaturn** [bradcornford/Sense-Hat-Snake#1]
Hi, when excute the code I have next crash:
``` python
Traceback (most recent call last):
  File "sensehatsnake/main.py", line 2, in <module>
    from lib.game import Game
  File "/home/pi/src/sensehat-snake/sensehatsnake/lib/game.py", line 2, in <module>
    from board import Board
ImportError: No module named 'board'
```
Also, I upgraded all `python3` packages in my raspbian. Thanks

**Comment by bradcornford** [comment]
Hi there,

Can you try running this under Python 2. Also ensure you try running the process from the root of the repo, i.e. `sudo python sensehatsnake/main.py`
